import numpy as np
hours_studied = np.array([5.4, 7.3, 2.1, 1.8, 6.7])
attendance = np.array([100, 91, 72, 48, 69])
previous_scores = np.array([70, 91, 58, 87, 76])
final_scores = np.array([57, 83, 39, 93, 100])
print(f"Hours Studied - Shape: {hours_studied.shape} and Data Type: {hours_studied.dtype}")
print(f"Attendance - Shape: {attendance.shape} and Data Type: {attendance.dtype}")
print(f"Previous Scores - Shape: {previous_scores.shape} and Data Type: {previous_scores.dtype}")
print(f"Final Scores - Shape: {final_scores.shape} and Data Type: {final_scores.dtype}")
print(f"Mean Final Score: {np.mean(final_scores)}")
print(f"Max Final Score: {np.max(final_scores)} and Min Final Score: {np.min(final_scores)}")
print(f"Standard deviation of final scores: {np.std(final_scores):.2f}")
print(f"Final Scores + Bonus: {final_scores + 5}")
print("Boolean Array of Scores at least 75:", final_scores > 75)
print(f"Scores at least 75: {final_scores[final_scores > 75]}")